//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nado
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Надо.
    /// </summary>
    // *** Start programmer edit section *** (Надо CustomAttributes)

    // *** End programmer edit section *** (Надо CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НадоE", new string[] {
            "надо as \'Надо\'"})]
    [View("НадоL", new string[] {
            "надо as \'Надо\'"})]
    public class Надо : ICSSoft.STORMNET.DataObject
    {
        
        private string fнадо;
        
        // *** Start programmer edit section *** (Надо CustomMembers)

        // *** End programmer edit section *** (Надо CustomMembers)

        
        /// <summary>
        /// надо.
        /// </summary>
        // *** Start programmer edit section *** (Надо.надо CustomAttributes)

        // *** End programmer edit section *** (Надо.надо CustomAttributes)
        [StrLen(255)]
        public virtual string надо
        {
            get
            {
                // *** Start programmer edit section *** (Надо.надо Get start)

                // *** End programmer edit section *** (Надо.надо Get start)
                string result = this.fнадо;
                // *** Start programmer edit section *** (Надо.надо Get end)

                // *** End programmer edit section *** (Надо.надо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Надо.надо Set start)

                // *** End programmer edit section *** (Надо.надо Set start)
                this.fнадо = value;
                // *** Start programmer edit section *** (Надо.надо Set end)

                // *** End programmer edit section *** (Надо.надо Set end)
            }
        }
        
        // *** Start programmer edit section *** (Надо.Печать CustomAttributes)

        // *** End programmer edit section *** (Надо.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (Надо.Печать method implementation)

            return;
            // *** End programmer edit section *** (Надо.Печать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НадоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НадоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НадоE", typeof(IIS.Nado.Надо));
                }
            }
            
            /// <summary>
            /// "НадоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НадоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НадоL", typeof(IIS.Nado.Надо));
                }
            }
        }
    }
}
